- id: doi:10.1109/imcom64595.2025.10857574
  image: 'images/thumbnails/Screenshot from 2025-04-10 04-21-10.png'
  buttons:
  - type: pdf
    link: pdf/Towards_Robust_Federated_Learning_Investigating_Poisoning_Attacks_Under_Clients_Data_Heterogeneity (1).pdf
- id: doi:10.1109/TR.2025.3551717
  image: 'images/thumbnails/Stealthy Query-Efficient Opaque Attack Against Interpretable Deep Learning.png'
  buttons:
  - type: pdf
    link: pdf/Stealthy_Query-Efficient_Opaque_Attack_Against_Interpretable_Deep_Learning.pdf
- id: doi:10.57197/JDR-2024-0101
  image: 'images/thumbnails/Responsible Artificial Intelligence for Mental Health Disorders: Current Applications and Future Challenges.png'
  buttons:
  - type: pdf
    link: pdf/resposible_artificial_intiligence.pdf
- id: doi:10.1109/ACCESS.2025.3547573
  image: 'images/thumbnails/FiSC: A Novel Approach for Fitzpatrick Scale-Based Skin Analyzer’s Image Classification.png'
  buttons:
  - type: pdf
    link: pdf/FiSC_A_Novel_Approach_for_Fitzpatrick_Scale-Based_Skin_Analyzers_Image_Classification (1).pdf
- id: doi:10.3390/diagnostics14212385
  image: 'images/thumbnails/Explainable Multi-Layer Dynamic Ensemble Framework Optimized for Depression Detection and Severity Assessment.png'
  buttons:
  - type: pdf
    link: pdf/Explainable Multi-Layer Dynamic Ensemble Framework Optimized for Depression Detection and Severity Assessment.pdf
- id: doi:10.1109/TDSC.2023.3341090
  image: 'images/thumbnails/Hardening Interpretable Deep Learning Systems: Investigating Adversarial Threats and Defenses.png'
  buttons:
  - type: pdf
    link: pdf/Hardening_Interpretable_Deep_Learning_Systems_Investigating_Adversarial_Threats_and_Defenses.pdf
- id: doi:10.3390/app13063937
  image: 'https://www.mdpi.com/applsci/applsci-13-03937/article_deploy/html/images/applsci-13-03937-g002.png'
  buttons:
  - type: pdf
    link: pdf/app13063937.pdf
- id: doi:10.1016/j.cmpb.2024.108348
  image: 'images/thumbnails/Alzheimers disease diagnosis in the metaverse.jpg'
  buttons:
  - type: pdf
    link: pdf/Alzheimers disease diagnosis in the metaverse.pdf
- id: doi:10.3390/info15100583
  image: 'images/thumbnails/Smart Collaborative Intrusion Detection System for Securing Vehicular Networks Using Ensemble Machine Learning Model.webp'
  buttons:
  - type: pdf
    link: pdf/Smart Collaborative Intrusion Detection System for Securing Vehicular Networks Using Ensemble Machine Learning Model.pdf
- id: doi:10.1109/TDSC.2023.3341090
  image: 'images/thumbnails/Hardening Interpretable Deep Learning Systems: Investigating Adversarial Threats and Defenses.png'
  buttons:
  - type: pdf
    link: pdf/Hardening_Interpretable_Deep_Learning_Systems_Investigating_Adversarial_Threats_and_Defenses.pdf
- id: doi:10.1109/TIFS.2024.3407652
  image: 'images/thumbnails/SingleADV: Single-Class Target-Specific Attack Against Interpretable Deep Learning Systems.png'
  buttons:
  - type: pdf
    link: pdf/SingleADV_Single-Class_Target-Specific_Attack_Against_Interpretable_Deep_Learning_Systems.pdf
- id: doi:10.3390/diagnostics13010162
  image: ''
  buttons:
  - type: pdf
    link: pdf/diagnostics13010162.pdf
- id: doi:10.3390/diagnostics13030492
  image: ''
  buttons:
  - type: pdf
    link: pdf/diagnostics13030492.pdf
- id: doi:10.3390/s22239250
  image: ''
  buttons:
  - type: pdf
    link: pdf/s22239250.pdf
- id: doi:10.3390/app12199710
  image: ''
  buttons:
  - type: pdf
    link: pdf/app12199710.pdf
- id: doi:10.3390/electronics11101648
  image: ''
  buttons:
  - type: pdf
    link: pdf/electronics11101648.pdf
- id: doi:10.3390/electronics10141733
  image: ''
  buttons:
  - type: pdf
    link: pdf/electronics10141733.pdf
- id: doi:10.1016/j.knosys.2020.106688
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_knosys_2020_106688.pdf
- id: doi:10.32604/cmc.2021.014446
  image: ''
  buttons:
  - type: pdf
    link: pdf/cmc_2021_014446.pdf
- id: doi:10.3390/app10217673
  image: ''
  buttons:
  - type: pdf
    link: pdf/app10217673.pdf
- id: doi:10.3390/math8111863
  image: ''
  buttons:
  - type: pdf
    link: pdf/math8111863.pdf
- id: doi:10.3390/electronics9091443
  image: ''
  buttons:
  - type: pdf
    link: pdf/electronics9091443.pdf
- id: doi:10.3390/electronics9091439
  image: ''
  buttons:
  - type: pdf
    link: pdf/electronics9091439.pdf
- id: doi:10.22266/ijies2020.0630.26
  image: ''
  buttons:
  - type: pdf
    link: pdf/ijies2020_0630_26.pdf
- id: doi:10.1109/tnse.2018.2877646
  image: ''
  buttons:
  - type: pdf
    link: pdf/tnse_2018_2877646.pdf
- id: doi:10.1186/s12911-019-0806-z
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12911-019-0806-z.pdf
- id: doi:10.3390/electronics8060635
  image: ''
  buttons:
  - type: pdf
    link: pdf/electronics8060635.pdf
- id: doi:10.3390/s19020234
  image: ''
  buttons:
  - type: pdf
    link: pdf/s19020234.pdf
- id: doi:10.1186/s13326-018-0176-y
  image: ''
  buttons:
  - type: pdf
    link: pdf/s13326-018-0176-y.pdf
- id: doi:10.1186/s12911-018-0651-5
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12911-018-0651-5.pdf
- id: doi:10.1038/s41598-023-42796-6
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41598-023-42796-6.pdf
- id: doi:10.3390/app13169425
  image: ''
  buttons:
  - type: pdf
    link: pdf/app13169425.pdf
- id: doi:10.20944/preprints202307.0585.v1
  image: ''
  buttons:
  - type: pdf
    link: pdf/preprints202307_0585_v1.pdf
- id: doi:10.3390/f14071325
  image: ''
  buttons:
  - type: pdf
    link: pdf/f14071325.pdf
- id: doi:10.1371/journal.pone.0285455
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0285455.pdf
- id: doi:10.1038/s41598-023-27815-w
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41598-023-27815-w.pdf
- id: doi:10.3390/su142315681
  image: ''
  buttons:
  - type: pdf
    link: pdf/su142315681.pdf
- id: doi:10.3390/math10050766
  image: ''
  buttons:
  - type: pdf
    link: pdf/math10050766.pdf
- id: doi:10.3390/math10030351
  image: ''
  buttons:
  - type: pdf
    link: pdf/math10030351.pdf
- id: doi:10.3390/electronics10161956
  image: ''
  buttons:
  - type: pdf
    link: pdf/electronics10161956.pdf
- id: doi:10.3390/e22080841
  image: ''
  buttons:
  - type: pdf
    link: pdf/e22080841.pdf
- id: doi:10.1101/2023.05.01.538993
  image: ''
  buttons:
  - type: pdf
    link: pdf/2023_05_01_538993.pdf
- id: doi:10.1186/s12859-019-3297-0
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12859-019-3297-0.pdf
- id: doi:10.1101/564187
  image: ''
  buttons:
  - type: pdf
    link: pdf/564187.pdf
- id: doi:10.1021/acs.jproteome.6b00938
  image: ''
  buttons:
  - type: pdf
    link: pdf/acs_jproteome_6b00938.pdf
- id: doi:10.1371/journal.pone.0173375
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0173375.pdf
- id: doi:10.3390/ma9030196
  image: ''
  buttons:
  - type: pdf
    link: pdf/ma9030196.pdf
- id: doi:10.1016/j.biomaterials.2013.10.007
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_biomaterials_2013_10_007.pdf
- id: doi:10.1101/2022.10.10.511492
  image: ''
  buttons:
  - type: pdf
    link: pdf/2022_10_10_511492.pdf
- id: doi:10.1017/cts.2023.619
  image: ''
  buttons:
  - type: pdf
    link: pdf/cts_2023_619.pdf
- id: doi:10.1186/s12859-023-05258-4
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12859-023-05258-4.pdf
- id: doi:10.37044/osf.io/3b9gp
  image: ''
  buttons:
  - type: pdf
    link: pdf/3b9gp.pdf
- id: doi:10.1038/s41597-023-01969-8
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41597-023-01969-8.pdf
- id: doi:10.1101/2022.01.27.22269965
  image: ''
  buttons:
  - type: pdf
    link: pdf/2022_01_27_22269965.pdf
- id: doi:10.15346/hc.v6i1.4
  image: ''
  buttons:
  - type: pdf
    link: pdf/hc_v6i1_4.pdf
- id: doi:10.1186/s12859-018-2041-5
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12859-018-2041-5.pdf
- id: doi:10.1101/156141
  image: ''
  buttons:
  - type: pdf
    link: pdf/156141.pdf
- id: doi:10.1101/038083
  image: ''
  buttons:
  - type: pdf
    link: pdf/038083.pdf
- id: doi:10.1016/j.gene.2016.04.053
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_gene_2016_04_053.pdf
- id: doi:10.1186/s13059-016-0953-9
  image: ''
  buttons:
  - type: pdf
    link: pdf/s13059-016-0953-9.pdf
- id: doi:10.1101/035667
  image: ''
  buttons:
  - type: pdf
    link: pdf/035667.pdf
- id: doi:10.1371/journal.ppat.1004045
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_ppat_1004045.pdf
- id: doi:10.1038/ja.2009.7
  image: ''
  buttons:
  - type: pdf
    link: pdf/ja_2009_7.pdf
- id: doi:10.1038/ja.2007.2
  image: ''
  buttons:
  - type: pdf
    link: pdf/ja_2007_2.pdf
- id: doi:10.1038/s41597-023-02534-z
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41597-023-02534-z.pdf
- id: doi:10.21203/rs.3.rs-1723808/v1
  image: ''
  buttons:
  - type: pdf
    link: pdf/v1.pdf
- id: doi:10.21203/rs.3.rs-1723829/v1
  image: ''
  buttons:
  - type: pdf
    link: pdf/v1.pdf
- id: doi:10.37044/osf.io/8qdse
  image: ''
  buttons:
  - type: pdf
    link: pdf/8qdse.pdf
- id: doi:10.1371/journal.pgen.1006997
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pgen_1006997.pdf
- id: doi:10.1101/121178
  image: ''
  buttons:
  - type: pdf
    link: pdf/121178.pdf
- id: doi:10.1186/s13195-023-01255-0
  image: ''
  buttons:
  - type: pdf
    link: pdf/s13195-023-01255-0.pdf
- id: doi:10.1038/s41597-023-01968-9
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41597-023-01968-9.pdf
- id: doi:10.1038/s41592-023-01769-3
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41592-023-01769-3.pdf
- id: doi:10.1111/cts.13302
  image: ''
  buttons:
  - type: pdf
    link: pdf/cts_13302.pdf
- id: doi:10.1186/s12915-020-00940-y
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12915-020-00940-y.pdf
- id: doi:10.3390/genes11111384
  image: ''
  buttons:
  - type: pdf
    link: pdf/genes11111384.pdf
- id: doi:10.1038/s41586-020-2577-1
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41586-020-2577-1.pdf
- id: doi:10.3389/fgene.2019.01355
  image: ''
  buttons:
  - type: pdf
    link: pdf/fgene_2019_01355.pdf
- id: doi:10.1371/journal.pone.0222165
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0222165.pdf
- id: doi:10.1126/sciimmunol.aaw6329
  image: ''
  buttons:
  - type: pdf
    link: pdf/sciimmunol_aaw6329.pdf
- id: doi:10.1101/444497
  image: ''
  buttons:
  - type: pdf
    link: pdf/444497.pdf
- id: doi:10.1038/s41746-018-0052-2
  image: ''
  buttons:
  - type: pdf
    link: pdf/s41746-018-0052-2.pdf
- id: doi:10.1101/367599
  image: ''
  buttons:
  - type: pdf
    link: pdf/367599.pdf
- id: doi:10.1186/s12864-018-4718-6
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12864-018-4718-6.pdf
- id: doi:10.1371/journal.pbio.2002846
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pbio_2002846.pdf
- id: doi:10.1002/pmic.201700391
  image: ''
  buttons:
  - type: pdf
    link: pdf/pmic_201700391.pdf
- id: doi:10.1016/j.molimm.2018.09.020
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_molimm_2018_09_020.pdf
- id: doi:10.1126/science.aao0462
  image: ''
  buttons:
  - type: pdf
    link: pdf/science_aao0462.pdf
- id: doi:10.5334/cstp.56
  image: ''
  buttons:
  - type: pdf
    link: pdf/cstp_56.pdf
- id: doi:10.1021/acs.jproteome.6b00095
  image: ''
  buttons:
  - type: pdf
    link: pdf/acs_jproteome_6b00095.pdf
- id: doi:10.1016/j.joca.2016.11.007
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_joca_2016_11_007.pdf
- id: doi:10.1016/j.joca.2016.04.015
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_joca_2016_04_015.pdf
- id: doi:10.1186/s12864-016-2855-3
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12864-016-2855-3.pdf
- id: doi:10.1186/s13326-016-0061-5
  image: ''
  buttons:
  - type: pdf
    link: pdf/s13326-016-0061-5.pdf
- id: doi:10.1371/journal.pone.0149621
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0149621.pdf
- id: doi:10.1126/scitranslmed.3009986
  image: ''
  buttons:
  - type: pdf
    link: pdf/scitranslmed_3009986.pdf
- id: doi:10.1186/s12920-015-0095-z
  image: ''
  buttons:
  - type: pdf
    link: pdf/s12920-015-0095-z.pdf
- id: doi:10.1142/9789814644730_0028
  image: ''
  buttons:
  - type: pdf
    link: pdf/9789814644730_0028.pdf
- id: doi:10.1101/009332
  image: ''
  buttons:
  - type: pdf
    link: pdf/009332.pdf
- id: doi:10.3389/fcimb.2014.00108
  image: ''
  buttons:
  - type: pdf
    link: pdf/fcimb_2014_00108.pdf
- id: doi:10.1186/s13059-014-0438-7
  image: ''
  buttons:
  - type: pdf
    link: pdf/s13059-014-0438-7.pdf
- id: doi:10.2196/games.3350
  image: ''
  buttons:
  - type: pdf
    link: pdf/games_3350.pdf
- id: doi:10.4049/jimmunol.1301279
  image: ''
  buttons:
  - type: pdf
    link: pdf/jimmunol_1301279.pdf
- id: doi:10.1186/2041-1480-4-S1-S4
  image: ''
  buttons:
  - type: pdf
    link: pdf/2041-1480-4-S1-S4.pdf
- id: doi:10.1371/journal.pone.0071171
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0071171.pdf
- id: doi:10.1371/journal.pone.0072511
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0072511.pdf
- id: doi:10.1016/j.celrep.2013.03.024
  image: ''
  buttons:
  - type: pdf
    link: pdf/j_celrep_2013_03_024.pdf
- id: doi:10.1371/journal.pcbi.1003244
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pcbi_1003244.pdf
- id: doi:10.1002/art.37760
  image: ''
  buttons:
  - type: pdf
    link: pdf/art_37760.pdf
- id: doi:10.1186/1741-7007-10-90
  image: ''
  buttons:
  - type: pdf
    link: pdf/1741-7007-10-90.pdf
- id: doi:10.1007/s00335-012-9408-0
  image: ''
  buttons:
  - type: pdf
    link: pdf/s00335-012-9408-0.pdf
- id: doi:10.1186/2041-1480-3-S1-S6
  image: ''
  buttons:
  - type: pdf
    link: pdf/2041-1480-3-S1-S6.pdf
- id: doi:10.1371/journal.pone.0025807
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0025807.pdf
- id: doi:10.1186/gb-2011-12-12-135
  image: ''
  buttons:
  - type: pdf
    link: pdf/gb-2011-12-12-135.pdf
- id: doi:10.1186/1471-2164-12-603
  image: ''
  buttons:
  - type: pdf
    link: pdf/1471-2164-12-603.pdf
- id: doi:10.1186/1752-0509-4-29
  image: ''
  buttons:
  - type: pdf
    link: pdf/1752-0509-4-29.pdf
- id: doi:10.1371/journal.pone.0013920
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0013920.pdf
- id: doi:10.1371/journal.pone.0014458
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0014458.pdf
- id: doi:10.1073/pnas.0914019107
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_0914019107.pdf
- id: doi:10.1371/journal.pone.0004649
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pone_0004649.pdf
- id: doi:10.1186/gb-2009-10-11-r130
  image: ''
  buttons:
  - type: pdf
    link: pdf/gb-2009-10-11-r130.pdf
- id: doi:10.1186/1472-6769-9-2
  image: ''
  buttons:
  - type: pdf
    link: pdf/1472-6769-9-2.pdf
- id: doi:10.1371/journal.pbio.0060175
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pbio_0060175.pdf
- id: doi:10.1371/journal.pgen.1000070
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pgen_1000070.pdf
- id: doi:10.1371/journal.pgen.1000232
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pgen_1000232.pdf
- id: doi:10.1186/gb-2007-8-4-404
  image: ''
  buttons:
  - type: pdf
    link: pdf/gb-2007-8-4-404.pdf
- id: doi:10.1073/pnas.0511292103
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_0511292103.pdf
- id: doi:10.1186/1471-2105-7-61
  image: ''
  buttons:
  - type: pdf
    link: pdf/1471-2105-7-61.pdf
- id: doi:10.1073/pnas.0409459102
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_0409459102.pdf
- id: doi:10.1091/mbc.E05-01-0062
  image: ''
  buttons:
  - type: pdf
    link: pdf/mbc_E05-01-0062.pdf
- id: doi:10.1073/pnas.0400782101
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_0400782101.pdf
- id: doi:10.1101/gr.2161804
  image: ''
  buttons:
  - type: pdf
    link: pdf/gr_2161804.pdf
- id: doi:10.1371/journal.pbio.0020393
  image: ''
  buttons:
  - type: pdf
    link: pdf/journal_pbio_0020393.pdf
- id: doi:10.1016/S0002-9440(10)64408-2
  image: ''
  buttons:
  - type: pdf
    link: pdf/S0002-9440(10)64408-2.pdf
- id: doi:10.1073/pnas.122359899
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_122359899.pdf
- id: doi:10.1073/pnas.202608199
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_202608199.pdf
- id: doi:10.1073/pnas.012025199
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_012025199.pdf
- id: doi:10.1073/pnas.041452598
  image: ''
  buttons:
  - type: pdf
    link: pdf/pnas_041452598.pdf
